version: '3'
services:

  nginx:
    environment:
      - NODE_ENV
      - USE_SSL
      - HOST
    build:
      context: ../
      dockerfile: docker/nginx-dockerfile
      args:
        - NODE_ENV
        - USE_SSL
        - HOST
    ports:
      - 80:80
      - 443:443
    volumes:
      -  ..:/app
    image: 'nginx:1'

